### ISSUE TITLE
Feature Request: Make it possible to run Make in the "official" make window from a addin

### ISSUE THREAD

**Issue by rkrug** [rstudio/rstudioapi#83] opened 2018-01-15 10:06 UTC
It is easily possible to rmake an addin which runs ```make``` and to display the results in a terminal window, but it would be really nice if I could use the same windos / viewer which is used for the build action "Makefile" as it is in the expected location when running make and offers more features.

The resoning is that it would sometimes be useful to run ```make``` even if e.g. the package development tools are selected.

**Comment by hadley** [comment] 2018-01-22 17:11
Duplicate of #17

**Closed by hadley** 2018-01-22 17:11 UTC
